### ISSUE TITLE
Cities:Skylines 2 support

### ISSUE THREAD

**Issue by erkinalp** [nonta1234/terraining-heightmap-generator#1]
## Default map size

World heightmap: 4096×4096px, PNG/TIFF/RAW, 16-bit greyscale (14.336km×14.336km)

Background map: 4096×4096px, PNG/TIFF/RAW, 16-bit greyscale (57.344km×57.344km)

## Larger map mod by @algernon-A

Heightmap: 16384×16384px, PNG/TIFF/RAW, 16-bit greyscale (57.344km×57.344km or 114.688km×114.688km)

**Comment by nonta1234** [comment]
Support for default map size in CS2 has been completed. I am currently testing and verifying for release.
Supporting Larger Map Mod will take a bit longer as it requires circumventing canvas limitations and a different approach.

**Comment by erkinalp** [comment]
I am having trouble with larger maps beyond 67 degrees north or south.

**Comment by nonta1234** [comment]
I also confirmed a similar issue. The cause has been identified, so I will improve it.
