### ISSUE TITLE
terrain littoral zone bug

### ISSUE THREAD

**Issue by Sunrisered** [nonta1234/terraining-heightmap-generator#13]
a strange ridge of terrain along water littoral zone,

**Comment by nonta1234** [comment]
Could you please show me a screenshot?

**Comment by Sunrisered** [comment]
![heightmap_153 14986915528948_-27 392659012939866_17 28](https://github.com/nonta1234/terraining-heightmap-generator/assets/169490397/eaf38fad-0f8c-4715-8a67-a87cfa6428ac)

**Comment by nonta1234** [comment]
Open the littoral editor and check the shape of the littoral.

**Comment by Sunrisered** [comment]
I set it on Sine but still there. I have managed to get it without that but then subsequent downloads return that almost backward littoral. I Changed littoral zone height to all kinds of heights between 160 and 0 mtr and no luck. Im using a brave browser so may try another later see if helps

**Comment by nonta1234** [comment]
I think this is a problem related to PixiJS. Currently, I am working on improving these WebGL issues.

**Comment by nonta1234** [comment]
v1.4.0
