### ISSUE TITLE
rotating the map area crashes browsers when generating heightmaps

### ISSUE THREAD

**Issue by SqyD** [nonta1234/terraining-heightmap-generator#14]
I've been trying to optimize the coverage area of a map but each time I rotate the map grid and export height data, the browser either crashes completely or it blanks to a white screen. Sometimes the terraining UI elements recover and the export proceeds but the generated maps are garbled. I experience this in Chrome and Edge on Windows 11 and on Chromium and Firefox in Debian Linux. Exporting the image works fine, even in the whitescreen + ui state. When not rotating all works fine too.

**Comment by SqyD** [comment]
[terraining.ateliernonta.com-1715512074717.log](https://github.com/nonta1234/terraining-heightmap-generator/files/15285974/terraining.ateliernonta.com-1715512074717.log)
A Console log from Chromium under Debian Linux. I hope that helps. Thanks!

**Comment by nonta1234** [comment]
I think this is a problem related to PixiJS. Currently, I am working on improving these WebGL issues.

**Comment by nonta1234** [comment]
v1.4.0
