### ISSUE TITLE
Downloading doesn't work

### ISSUE THREAD

**Issue by flya00** [nonta1234/terraining-heightmap-generator#18]
I've been trying to download a PNG map for several hours and nothing works.

Troubleshooting steps I tried
- Used both Windows and MacOS
- Tried downloading every file type, RAW, PNG, IMG, and OSM (IMG and OSM work every-time, RAW and PNG never work)
- Tried changing Access Token
- Used Microsoft Edge, Google Chrome, Firefox, Safari, and Arc browser
- Tried VPN and using Cellular Data instead of WiFi
- Cleared full browser history and cookies
- Reset browser settings
- Uninstall all extensions
- Waited upto 45 mins per download but nothing happened

The download function for RAW and PNG just seems to be entirely broken, I don't know what else I can try, I was really hoping to import a heightmap into CS2 today but I don't think that's going to happen. Some others online also have the same issues as me. Can you look into the issue? Thanks.

**Comment by Spilkey** [comment]
Can confirm this issue is also occurring for me. Console output is seen below

![image](https://github.com/nonta1234/terraining-heightmap-generator/assets/33938665/50e496f9-453b-46bf-b49e-e0914ae5fd3f)

**Comment by nonta1234** [comment]
It was a module import mistake during build. Fixed. thank you.
