### ISSUE TITLE
Rivers & streams not correctly created

### ISSUE THREAD

**Issue by motusmusic** [nonta1234/terraining-heightmap-generator#19]
Importing Hightmap into the game has parts of rivers & streams missing.

**Comment by nonta1234** [comment]
In the source, only the narrow part is a stream, so not everything is connected. If the slope on the land side of the littoral is made a little steeper, the phenomenon of the river disappearing will be alleviated. There is no way to distinguish between oceans and rivers in the mapbox layer, so this seems to be the only workaround.

**Comment by motusmusic** [comment]
This makes sence. It's where the rivers are quite narrow they vanish. Reducing littoral zone setting makes smaller rivers show on map. Thank You :)
