### ISSUE TITLE
Need to be able to set a smaller scale

### ISSUE THREAD

**Issue by BrokVid** [nonta1234/terraining-heightmap-generator#2]
The picture is a great example that at the minimum scale in your application - CS2 objects are slightly larger than real ones. This is just one example, but even game road junctions look 1.5-2 times larger.

In general, please make it possible to set a smaller scale (now it is automatically overwritten). I think I need Map size 42 or even smaller.

![Cities2_yIOBHr3Z1i](https://github.com/nonta1234/terraining-heightmap-generator/assets/23031579/016ec7a0-2509-4e71-9655-55de67fe1a08)

**Comment by BrokVid** [comment]
In my example, the city used is Ekaterinburg, lng 60.60628, lat 56.83764
and as you can see, the city more than fits, but with such a map size it is simply impossible to build it in detail, with all the alleys and pedestrian paths.

I'd like to reduce the map size to bring the size down to the real size.

**Comment by nonta1234** [comment]
v1.1.0 
Update map resizing

**Comment by Ungov77** [comment]
on https://terraining.ateliernonta.com/ i still can't set a real-life scale of 14km for the map instead of 28km :(

**Comment by nonta1234** [comment]
> on https://terraining.ateliernonta.com/ i still can't set a real-life scale of 14km for the map instead of 28km :(

The default map size for CS2 is 57.344km. In that case, the size of the playable area is 14.336 km. Setting the size to 28.672km means the playable area will be 7.168km.

Do you want a quarter of the default size?
