### ISSUE TITLE
Distorted map edges when imported in Unity 2020. (Non CS2)

### ISSUE THREAD

**Issue by T0Pping** [nonta1234/terraining-heightmap-generator#24]
Hi, I appreciate that this is beyond the scope of the programs intended use but given that this seems to be one of the last surviving heightmap creators at the moment I felt that I had nothing to lose by trying here. When attempting to import the RAW export file into Unity 2020.3 I am finding that two of the four terrain edges are featuring heavy distortion on any land that isn't sea level. Given that it is not the intended purpose for this program feel free to ignore but I just wanted to try here as one last hail Mary.

![image](https://github.com/nonta1234/terraining-heightmap-generator/assets/87346212/3f88a875-ac50-4e5b-8868-4c8851ddb216)
![image](https://github.com/nonta1234/terraining-heightmap-generator/assets/87346212/f58b00fa-a846-4c68-b25d-6c6ecee905e6)

**Comment by nonta1234** [comment]
I'm not familiar with Unity, but maybe it's a problem with the resolution settings when importing?

**Comment by T0Pping** [comment]
I tweaked about every import setting I could find and couldn't seem to fix it. It isn't the end of the world, I just need to run the smooth brush down the two edges and it fixes 99% of the issue. Thanks for providing a awesome (and one of the last remaining) height mappers though!

**Comment by nonta1234** [comment]
Supported in v2.0.0
