### ISSUE TITLE
[v1.5.0](https://github.com/nonta1234/terraining-heightmap-generator/releases/tag/v1.5.0) available.

### ISSUE THREAD

**Issue by zuben00** [nonta1234/terraining-heightmap-generator#26]
[v1.5.0](https://github.com/nonta1234/terraining-heightmap-generator/releases/tag/v1.5.0) available.

_Originally posted by @nonta1234 in https://github.com/nonta1234/terraining-heightmap-generator/issues/21#issuecomment-2169159359_
            

Thank you for the feature update.

1.5.0
Mapbox zoom level does not match the zoom level.
I had to enter a zoom level of '14' in the custom map image option to download an image with the railroad bridge information at the '13' level that I had previously presented.

1.5.2
After the update, images with 2560*2560 size will be downloaded only if both 'Zoom type' and 'Size type' are 'Auto'. If you enter a level or size, it will output an 'undefined' message and the image will not download. 

![s_pic254](https://github.com/nonta1234/terraining-heightmap-generator/assets/166455485/04e9584c-ccce-4ef4-ae9b-b1fdffafd58f)

**Comment by nonta1234** [comment]
It seems that there was an error in the calculation logic. Fixed.

[v1.5.3](https://github.com/nonta1234/terraining-heightmap-generator/releases/tag/v1.5.3)
