### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by DisFeed** [nonta1234/terraining-heightmap-generator#34]
500
Failed to initialize WebGL.

https://terraining.ateliernonta.com/

**Comment by nonta1234** [comment]
Could you please tell me the details?

**Comment by DisFeed** [comment]
I am unfamilar with Nuxt. Your website is showing that error.,
Visit your domain, and you will see it's not working.

**Comment by DisFeed** [comment]
Appears to be a problem with my client. Tried it on another browser and works fine. Not sure exactly what the problem was, but apologies for creating issue.
