### ISSUE TITLE
Unable to download heightmap

### ISSUE THREAD

**Issue by jfranecki** [nonta1234/terraining-heightmap-generator#36]
When selecting a location and then pressing the PNG heightmap button, I see "Downloading Elevation Data: 25/25" then nothing happens. It worked yesterday, but now with version 2.0, I cannot seem to download a heightmap. I am using Firefox.

**Comment by shanesype** [comment]
I am having a similar issue.  When this happens does this message appear in your browser's development console?

```
Geometry exceeds allowed extent, reduce your vector tile buffer size 2d01b3b5-e3fd-43ce-8bf7-89eedc24acd1:1:69198
```

**Comment by nonta1234** [comment]
I tested the download using Firefox, and there were no problems. Try resetting it in the config tab.

If that doesn't solve the problem, could you please export the settings file and upload it here? The json file does not contain any keys or tokens, so it is safe.

**Comment by jfranecki** [comment]
I am out of town for the weekend, will try again Sunday night and update you. As a note, I have both the MapTiler and Mapbox API keys entered. Neither PNG nor RAW heightmaps could be downloaded, but downloading other map formats seemed to work just fine.

**Comment by nonta1234** [comment]
> I am having a similar issue. When this happens does this message appear in your browser's development console?
> 
> ```
> Geometry exceeds allowed extent, reduce your vector tile buffer size 2d01b3b5-e3fd-43ce-8bf7-89eedc24acd1:1:69198
> ```

This error message is a known issue with Mapbox GL JS, but it doesn't seem to be directly related to map downloads.

**Comment by jfranecki** [comment]
> I tested the download using Firefox, and there were no problems. Try resetting it in the config tab.
> 
> If that doesn't solve the problem, could you please export the settings file and upload it here? The json file does not contain any keys or tokens, so it is safe.

Resetting fixed the issue. I can now download heightmap in png.
