### ISSUE TITLE
Not working in Microsoft Edge

### ISSUE THREAD

**Issue by delebash** [nonta1234/terraining-heightmap-generator#37]
MS Edge version  131.0.2903.99 (Official build) (64-bit)

1. No map is displayed
2. Works fine in Chrome and Firefox, map loads as expected.

Tried the reset button, even opened debug tools and cleared local storage.  Also tried on another computer.  Strange problem.

Nice job on the update I love the UE and Unity additions.  

![Screenshot 2024-12-13 192801](https://github.com/user-attachments/assets/c2fe89c3-5226-4411-a205-277f5a14a20b)

**Comment by nonta1234** [comment]
I tested it in the same environment.

MS Edge version 131.0.2903.99 (Official build) (64-bit)

The map will display without any problems here. As far as I can see the error, Mapbox access is denied. As you said, this is a strange error.

Sorry, please try reloading several times.

**Comment by delebash** [comment]
Thanks, I will try reinstalling.  Since you are not having a problem with Edge I will close this.
