### ISSUE TITLE
No min max height 

### ISSUE THREAD

**Issue by Qsessi** [nonta1234/terraining-heightmap-generator#7]
Every time I press the refresh button, the min and max height are still 0 is there an issue or am i doing something wrong

**Comment by nonta1234** [comment]
> Every time I press the refresh button, the min and max height are still 0 is there an issue or am i doing something wrong

I would like to check the situation, so could you please tell me the latitude and longitude where the issue occurs?

**Comment by Qsessi** [comment]
This happens everywhere all over the map, no map data seems to be gathered. I tested it all over the world.

**Comment by Qsessi** [comment]
i can add a picture
![image_2024-03-21_112754471](https://github.com/nonta1234/terraining-heightmap-generator/assets/162049394/854f82d3-570a-483b-93e1-5dcd95014543)

**Comment by Qsessi** [comment]
![Screenshot 2024-03-21 112844](https://github.com/nonta1234/terraining-heightmap-generator/assets/162049394/bd23ef64-1239-46c0-888d-6c30699c26f9)
![Screenshot 2024-03-21 112952](https://github.com/nonta1234/terraining-heightmap-generator/assets/162049394/480867f0-a2ed-4793-b0bc-d4d95cb20abe)

**Comment by nonta1234** [comment]
I confirmed that the number "11234" was entered in the access token field. what number is that?
For CS2, if you do not enter the correct Mapbox access token, the access is denied and you will not be able to retrieve elevation data.

**Comment by Qsessi** [comment]
ohhh ok so how do i get the access token sorry for wasting your time

**Comment by Qsessi** [comment]
thank you

**Comment by TheBango** [comment]
Although this issue has been marked as solved, I want to leave a tip for users which may encounter this issue in the future:
If you don't get height data after using the reload function, you may have to go to your Mabpox account, refresh your public token and then enter the new key in settings of the terrain generator. It worked for me!
