### ISSUE TITLE
Map Image uses worldmap area isntead of playable area

### ISSUE THREAD

**Issue by Mav12222** [nonta1234/terraining-heightmap-generator#8]
Right now, when I download a street map using the map image function, It downloads the zoomed out world map area.  This is too far out to detail the streets for the map image layer.  Since the minimum size is 28km2, you cannot reduce the map area download to the size of the playable area.

A solution would be to allow a reduction in size to the Csky2 playable area, or an option to only download a map image of the playable area at that size.

**Comment by nonta1234** [comment]
I will fix it soon.

**Comment by nonta1234** [comment]
v1.3.0
